import os
import socket
import struct
import threading


class PacketCapture:
    """Capture IPv4 packets and pass parsed packets to a callback."""

    def __init__(
        self,
        packet_parser,
        packet_callback,
        ignored_ips=None
    ):
        """Initialise the packet capture worker."""
        self.packet_parser = packet_parser
        self.packet_callback = packet_callback

        self.ignored_ips = set(
            ignored_ips or []
        )

        self.running = False
        self.thread = None
        self.sniffer = None

    def start(self, active_ip, session_id=0):
        """Start packet capture in a background thread."""
        if self.running:
            return

        self.running = True

        self.thread = threading.Thread(
            target=self._capture_loop,
            args=(active_ip, session_id),
            daemon=True
        )

        self.thread.start()

    def stop(self):
        """Stop packet capture and wait for the capture thread to finish."""
        self.running = False

        if self.sniffer:
            try:
                if os.name == "nt":
                    self.sniffer.ioctl(
                        socket.SIO_RCVALL,
                        socket.RCVALL_OFF
                    )
            except OSError:
                pass

            try:
                self.sniffer.close()
            except OSError:
                pass

            self.sniffer = None

        # Wait for the old capture worker to finish before allowing
        # another capture session to start.
        if (
            self.thread
            and self.thread.is_alive()
            and self.thread is not threading.current_thread()
        ):
            self.thread.join(
                timeout=1.0
            )

        self.thread = None

    def _capture_loop(self, active_ip, session_id):
        """Capture packets until the worker is stopped."""
        try:
            self.sniffer = socket.socket(
                socket.AF_INET,
                socket.SOCK_RAW,
                socket.IPPROTO_IP
            )

            self.sniffer.bind(
                (active_ip, 0)
            )

            self.sniffer.setsockopt(
                socket.IPPROTO_IP,
                socket.IP_HDRINCL,
                1
            )

            if os.name == "nt":
                self.sniffer.ioctl(
                    socket.SIO_RCVALL,
                    socket.RCVALL_ON
                )

            self.sniffer.settimeout(
                0.5
            )

            while self.running:
                try:
                    raw_data, _ = self.sniffer.recvfrom(
                        65535
                    )

                except socket.timeout:
                    continue

                except OSError:
                    if self.running:
                        self.packet_callback(
                            None,
                            "Packet capture socket error.",
                            session_id
                        )

                    break

                try:
                    packet = self.packet_parser(
                        raw_data
                    )

                except (ValueError, struct.error):
                    continue

                # Ignore both directions of traffic generated by services
                # that the application uses for network metadata enrichment.
                if (
                    packet["source_ip"] in self.ignored_ips
                    or packet["destination_ip"] in self.ignored_ips
                ):
                    continue

                packet["packet_length"] = len(
                    raw_data
                )

                self.packet_callback(
                    packet,
                    None,
                    session_id
                )

        except OSError as error:
            self.packet_callback(
                None,
                f"Unable to start packet capture: {error}",
                session_id
            )

        finally:
            self.running = False

            if self.sniffer:
                try:
                    if os.name == "nt":
                        self.sniffer.ioctl(
                            socket.SIO_RCVALL,
                            socket.RCVALL_OFF
                        )
                except OSError:
                    pass

                try:
                    self.sniffer.close()
                except OSError:
                    pass

                self.sniffer = None